SUBROUTINE LINMINSTRUCT(P,XI,FRET)

USE commondata, ONLY: num,tolstruc
USE cgdata, ONLY: PCOMSTRUCT,XICOMSTRUCT

use mpipara 
IMPLICIT NONE

INTEGER :: N,J
DOUBLE PRECISION, INTENT(OUT) :: FRET
DOUBLE PRECISION, DIMENSION(3*num+6), INTENT(INOUT) :: P,XI
DOUBLE PRECISION :: AXX,BXX,XX,FA,FX,FB,XMIN,DBRENT,F1DIMSTRUCT, DF1DIMSTRUCT 

EXTERNAL F1DIMSTRUCT,DF1DIMSTRUCT

PCOMSTRUCT=P
XICOMSTRUCT=XI
AXX=0.00D0
XX=1.00D0 / 1
BXX=2.00D0 / 1
 if (iam.eq.0) write (6,*) 'Entering Bracket '
CALL MNBRAKSTRUCT(AXX,XX,BXX,FA,FX,FB)
 if (iam.eq.0) write (6,*) 'Bracket Done', FA, FX, FB 
 if (iam.eq.0) write (6,*) 'Bracket Done', AXX,XX, BXX
FRET=DBRENT(AXX,XX,BXX,F1DIMSTRUCT,DF1DIMSTRUCT,TOLSTRUC,XMIN)
! FRET=BRENT(AXX,XX,BXX,F1DIMSTRUCT,TOLSTRUC,XMIN)
 if (iam.eq.0) write (6,*) 'DBRENT Done ', AXX, XX, BXX, XMIN, FRET 

XI=XMIN*XI
P=P+XI

RETURN
END SUBROUTINE
