SUBROUTINE MNBRAKSTRUCT(AXX,BXX,CX,FA,FB,FC)

use mpipara 
IMPLICIT NONE

DOUBLE PRECISION :: AXX,BXX,CX,FA,FB,FC,F1DIMSTRUCT
DOUBLE PRECISION :: DUM,R,QQ,U,ULIM,FU
DOUBLE PRECISION, PARAMETER :: GOLD=1.618034, GLIMIT=100., TINY=1.E-20

FA=F1DIMSTRUCT(AXX)

if (iam.eq.0) write (6,*) 'AXX= ',AXX, BXX, CX  
if (iam.eq.0) write (6,*) 'FA = ',FA, AXX 

FB=F1DIMSTRUCT(BXX)

if (iam.eq.0) write (6,*) 'FB = ',FB, BXX

IF(FB.GT.FA)THEN
   DUM=AXX
   AXX=BXX
   BXX=DUM
   DUM=FB
   FB=FA
   FA=DUM
ENDIF
CX=BXX+GOLD*(BXX-AXX)
FC=F1DIMSTRUCT(CX)
1     IF(FB.GE.FC)THEN
   R=(BXX-AXX)*(FB-FC)
   QQ=(BXX-CX)*(FB-FA)
   U=BXX-((BXX-CX)*QQ-(BXX-AXX)*R)/(2.*SIGN(MAX(ABS(QQ-R),TINY),QQ-R))
   ULIM=BXX+GLIMIT*(CX-BXX)
   IF((BXX-U)*(U-CX).GT.0.)THEN
     FU=F1DIMSTRUCT(U)
     IF(FU.LT.FC)THEN
       AXX=BXX
       FA=FB
       BXX=U
       FB=FU
       GO TO 1
     ELSE IF(FU.GT.FB)THEN
       CX=U
       FC=FU
       GO TO 1
     ENDIF
     U=CX+GOLD*(CX-BXX)
     FU=F1DIMSTRUCT(U)
   ELSE IF((CX-U)*(U-ULIM).GT.0.)THEN
     FU=F1DIMSTRUCT(U)
     IF(FU.LT.FC)THEN
       BXX=CX
       CX=U
       U=CX+GOLD*(CX-BXX)
       FB=FC
       FC=FU
       FU=F1DIMSTRUCT(U)
     ENDIF
   ELSE IF((U-ULIM)*(ULIM-CX).GE.0.)THEN
     U=ULIM
     FU=F1DIMSTRUCT(U)
   ELSE
     U=CX+GOLD*(CX-BXX)
     FU=F1DIMSTRUCT(U)
   ENDIF
   AXX=BXX
   BXX=CX
   CX=U
   FA=FB
   FB=FC
   FC=FU
   GO TO 1
ENDIF
RETURN
END SUBROUTINE
